# Problem 1
Arrays

In [ ]:
import numpy

def arrays(arr):
    arr = numpy.array(arr, float)
    return arr[::-1]

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


# Problem 2
Shape and Reshape

In [ ]:
import numpy

arr = numpy.array(input().strip().split(), int)
print(numpy.reshape(arr, (3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Problem 3
Transpose and Flatten

In [ ]:
import numpy

n, m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


# Problem 4
Concatenate

In [ ]:
import numpy as np

n, m, p = map(int,input().split())
A = np.array([input().split() for _ in range(n)],int)
B = np.array([input().split() for _ in range(m)],int)
print(np.concatenate((A, B), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


# Problem 5
Zeros and Ones

In [ ]:
import numpy

nums = tuple(map(int, input().split()))
print (numpy.zeros(nums, dtype = numpy.int))
print (numpy.ones(nums, dtype = numpy.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# Problem 6
Eye annd Identity

In [ ]:
import numpy

arr = tuple(map(int, input().split()))
A = numpy.eye(arr[0], arr[1])
print(str(A).replace('1', ' 1').replace('0', ' 0'))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Problem 7
Array Mathemetics

In [ ]:
import numpy as np

n, m = map(int, input().split())
a = np.array([input().split() for _ in range(n)], dtype=int) 
b = np.array([input().split() for _ in range(n)], dtype=int) 
print(a+b, a-b, a*b, a//b, a%b, a**b, sep='\n')

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


# Problem 8
Floor, Ceil and Rint

In [1]:
import numpy

numpy.set_printoptions(sign=' ')

a = numpy.array(input().split(),float)

print(numpy.floor(a))
print(numpy.ceil(a))
print(numpy.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


# Problem 9
Sum and Prod

In [3]:
import numpy
N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)],int)
print(numpy.prod(numpy.sum(A, axis=0), axis=0))

2 2
1 2
3 4
24


# Problem 10
Min and Max

In [4]:
import numpy as np

n, m = list(map(int, (input().split())))
a = np.array([list(map(int,(input().split()))) for i in range(int(n))])
print(np.max(np.min(a, axis = 1), axis = None))

4 2
2 5
3 7
1 3
4 0
3


# Problem 11
Mean, Var and Std

In [6]:
import numpy as np
n, m = map(int, input().split())
k = np.array([input().split() for _ in range(n)],dtype = int)
std = round(np.std(k), 11)
print(np.mean(k,axis=1), np.var(k,axis=0), std, sep='\n')

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


# Problem 12
Dot and Cross Discussion

In [7]:
import numpy
a=int(input())
arr1=numpy.array([list(map(int,input().split())) for _ in range(a)])
arr2=numpy.array([list(map(int,input().split())) for _ in range(a)])
print(numpy.dot(arr1,arr2))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


# Problem 13
Inner and Outer Discussion

In [8]:
import numpy as np
A = np.array(input().split(), int)
B = np.array(input().split(), int)
print(np.inner(A,B), np.outer(A,B), sep='\n')

0 1
2 3
3
[[0 0]
 [2 3]]


# Problem 14
Polynomials Discussions

In [9]:
import numpy
n = list(map(float,input().split()))
m = input()
print(numpy.polyval(n,int(m)))

1.1 2 3
0
3.0


# Problem 15
Linear Algebra Discussions

In [10]:
import numpy
print(round(numpy.linalg.det(numpy.array([list(map(float,input().split())) for _ in range(int(input()))])),2))

2
1.1 1.1
1.1 1.1
0.0
